### PR TITLE
Implement RivetInterface and make RivetAndroid extend it.

### PR DESCRIPTION
**Pull request by greglaun**
Implement RivetInterface and make RivetAndroid extend it. RivetBase now implements RivetInterface.

### CODE REVIEW

**Comment by msgilligan** [comment]
Actually, Greg, this is failing on Gitlab CI: https://gitlab.com/rivetz/RivetzJ/builds/6599345

**Comment by greglaun** [comment]
Sorry, I fixed it locally but forgot to push. I just pushed a fix.

**Comment by mespr** [comment]
Makes sense, looks good.

**Comment by hobnobber** [comment]
Looks good. Thanks

**Pull request merged**
